# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'v1rgo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for v1rgo
  #pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # pod 'native-navigation', :path => '../node_modules/native-navigation'

  target 'v1rgoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
